name: Ingress Workflow

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day
  workflow_dispatch:

jobs:
  ingress_workflow:
    runs-on: self-hosted
    name: Ingress Workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Make script executable
        run: chmod +x download_unzip_cleanup.sh

      - name: Run download_unzip_cleanup.sh
        run: ./download_unzip_cleanup.sh

      - name: Install Python requirements
        run: |        
          pip install -r requirements.txt

      - name: Run ingress.py
        run: |
          python3 ingress.py

      - name: Run update.py
        run: |
          python3 update.py
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Commit and push changes
        run: |
          git config --local user.email "adg@adgstudios.co.za"
          git config --local user.name "adgsenpai"
          git pull
          git add .
          git commit -m "DMCA Update $(git rev-parse --short HEAD)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
